name: turf
description: A turf.js-like geospatial analysis library working with GeoJSON, written in pure Dart.
version: 0.0.2+3
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://github.com/dartclub/turf_dart
repository: https://github.com/dartclub/turf_dart

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10
